name: Daily Commit

on:
  schedule:
    # Runs at 8:00 UTC every day
    - cron: '0 8 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create or update file with timestamp
      run: |
        echo "Last run: $(date -u)" > last_run.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '24f1001940@ds.study.iitm.ac.in'
        git add last_run.txt
        git commit -m "Daily update: $(date -u)"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
