name: Automated Daily Commit

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 2:30 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Updating log file (24f1001940@ds.study.iitm.ac.in)"  # Email explicitly in the name
        run: |
          echo "Last update: $(date)" >> update-log.txt

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "24f1001940@ds.study.iitm.ac.in"

      - name: Commit and push changes
        run: |
          git add update-log.txt
          git commit -m "Automated commit: $(date)"
          git push
